### ISSUE TITLE
Youtube Module

### ISSUE THREAD

**Issue by svaj** [sopel-irc/sopel-extras#70]
Continuing from https://github.com/embolalia/willie/issues/764#event-289704633

The old youtube module no longer works and will be remvoed from the willie repository.  I would like to open up a feature request here, in willie-extras for a new youtube module that would work with the v3 api.

**Comment by calzoneman** [comment]
I made [such a module](https://gist.github.com/calzoneman/b5ee12cf69863bd3fcc3) for a few channels I'm in that run willie.  It largely mimics the behavior of the old YouTube module (I omitted the `.ytlast` command since none of the channels I'm in used it, but it shouldn't be difficult to implement).

Please let me know if you'd like to include this and I can make a pull request (or you can just drop the file in yourself, I don't mind).  Let me know if there are any issues with the license; I'm willing to negotiate it.

**Comment by dgw** [comment]
There's https://github.com/sopel-irc/sopel-youtube for this. Closing, because it's going to stay separate (and we don't want to add new modules to extras, at this point).
